apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lysao58xf-go
  janus-idp.io/tekton: lysao58xf-go
  backstage.io/kubernetes-id: lysao58xf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lysao58xf-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
